version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
            name: Install CMake
            command: |
              sudo apt -y -q update
              sudo apt -y -q install cmake
      - checkout
      - run: cd test/googletest-release-1.10.0/; mkdir build; cd build; cmake ..; make
      - run: ls test/googletest-release-1.10.0
      - run: ls test/googletest-release-1.10.0/build
      - run: ls test/googletest-release-1.10.0/build/lib
      - run: ls test/googletest-release-1.10.0/googletest
      - run: cd test; make
