name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p test/googletest-release-1.10.0/build
      - run: cd build; cmake ..; make
      - run: ls
      - run: ls test
      - run: ls test/googletest-release-1.10.0
      - run: ls test/googletest-release-1.10.0/build
      - run: cd test; make
      - run: ls
      - run: ls test
