name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd test/googletest-release-1.10.0/
      - run: ls
      - run: mkdir build
      - run: ls
      - run: cd build
      - run: ls
      - run: cmake ..
      - run: ls
      - run: make
      - run: ls
      - run: cd test
      - run: ls
      - run: make
      - run: ls
      - run: ls test
