name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd test/googletest-release-1.10.0/; mkdir build; cd build; cmake ..; make
      - run: cd test; make
      - run: ls test
