name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GoogleTest
        run: |
          sudo apt install libgtest-dev

      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
          dotnet-quality: 'ga'

      - name: Build and Run-Test
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
          ./statemachine-test

      - name: Execute gcov
        run: |
          cd build/CMakeFiles/statemachine-test.dir/src
          gcov *.gcda

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: build/CMakeFiles/statemachine-test.dir/src/*.gcov
          targetdir: CoverageReport
          reporttypes: Html;MarkdownSummaryGithub;Badges

      - name: Upload CoverageReport
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./CoverageReport

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-package
          path: build

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: CoverageReport/SummaryGithub.md

  generate-doc:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate document
        uses: mattnotmitt/doxygen-action@1.9.5
    
      - name: Upload document
        uses: actions/upload-artifact@v3
        with:
          name: document
          path: ./html

  deploy-doc:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: [ "unittest", "generate-doc" ]
    steps:
      - name: Checkout document repository
        uses: actions/checkout@v3
        with:
          repository: asabon/Documents
          path: doc
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true

      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: ./temp/coverage-report

      - name: Download document
        uses: actions/download-artifact@v3
        with:
          name: document
          path: ./temp/document

      - name: Check result
        run: |
          echo "=== ls temp ==="
          ls temp
          echo "=== ls temp/coverage-report ==="
          ls temp/coverage-report
          echo "=== ls temp/document ==="
          ls temp/document
      
      - name: Delete items
        run: |
          rm -rf doc/StateMachine/*
      
      - name: Copy coverage-report to destination
        run: |
          mkdir -p doc/StateMachine/coverage-report
          cp -r ./temp/coverage-report/* doc/StateMachine/coverage-report/
  
      - name: Copy document to destination
        run: |
          mkdir -p doc/StateMachine/document
          cp -r ./temp/document/* doc/StateMachine/document/

      - name: Commit files to git repository
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          cd doc/StateMachine
          git add -A
          if ! git diff --cached --quiet; then
            git commit -a -m "Add changes"
          fi

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.8.0
        with:
          directory: doc/StateMachine
          repository: asabon/Documents
          ssh: true
