name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install GoogleTest
        run: |
          sudo apt install libgtest-dev

      - name: Build
        run: |
          mkdir -p test/build
          cd test/build
          cmake ..
          make

      - run: ls
      - run: ls test
      - run: ls test/build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-package
          path: test/build

        #      - name: run test
#        run: test/build/statemachine-test

#      - run: cd test/googletest-release-1.10.0/build; cmake ..; make
#      - run: ls
#      - run: ls test
#      - run: ls test/googletest-release-1.10.0
#      - run: ls test/googletest-release-1.10.0/build
#      - run: cd test; make
#      - run: ls
#      - run: ls test
