name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GoogleTest
        run: |
          sudo apt install libgtest-dev

      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
          dotnet-quality: 'ga'

      - name: Build and Run-Test
        run: |
          mkdir -p test/build
          cd test/build
          cmake ..
          make
          ./statemachine-test

      - name: gcov
        run: |
          cd test/build/CMakeFiles/statemachine-test.dir
          gcov *.gcda

      - run: ls test/build
      - run: ls test/build/CMakeFiles
      - run: ls test/build/CMakeFiles/statemachine-test.dir
    
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: test/build/CMakeFiles/statemachine-test.dir/*.gcda
          targetdir: CoverageReport
          reporttypes: Html;MarkdownSummaryGithub;Badges

      - name: Upload CoverageReport
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./CoverageReport

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-package
          path: test/build

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: CoverageReport/SummaryGithub.md
