name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create build directory
        run: mkdir -p test/build

      - name: download GoogleTest and build test
        run: |
          cd test/build
          cmake ..
          cmake --build .

      - run: ls
      - run: ls test
      - run: ls test/build

      - name: run test
        run: test/build/statemachine-test

#      - run: cd test/googletest-release-1.10.0/build; cmake ..; make
#      - run: ls
#      - run: ls test
#      - run: ls test/googletest-release-1.10.0
#      - run: ls test/googletest-release-1.10.0/build
#      - run: cd test; make
#      - run: ls
#      - run: ls test
