name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install GoogleTest
        run: |
          sudo apt install libgtest-dev

      - name: Build
        run: |
          mkdir -p test/build
          cd test/build
          cmake ..
          make
          ./statemachine-test

      - name: View file lists
        run: |
          cd test/build
          ls

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-package
          path: test/build
